import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Mic, Calendar, Plus, HelpCircle, Settings, CheckCircle, ChevronLeft, ChevronRight, } from "lucide-react";
const introSteps = [
    {
        title: "Welkom bij Huiswerkcoach Noukie! 👋",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-muted-foreground", children: "Ik ben je persoonlijke huiswerkcoach en help je elke dag om je huiswerk goed te plannen en uit te voeren." }), _jsxs("div", { className: "bg-purple-50 p-4 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-purple-800 mb-2", children: "Wat kan ik voor je doen?" }), _jsxs("ul", { className: "space-y-2 text-sm text-purple-700", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Dagelijkse voice check-ins voor takenplanning"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Huiswerkuitleg met foto's en stap-voor-stap hulp"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Slimme roosterplanning en herinneringen"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Ouders kunnen je voortgang volgen"] })] })] })] })),
    },
    {
        title: "🎙️ Vandaag Tab - Je Dagelijkse Check-in",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-blue-50 rounded-lg", children: [_jsx(Mic, { className: "w-8 h-8 text-blue-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-blue-800", children: "Voice Check-ins" }), _jsx("p", { className: "text-sm text-blue-600", children: "Vertel elke dag wat je hebt gedaan en wat er nog moet gebeuren" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Hoe werkt het?" }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "1" }), _jsx("p", { children: "Klik op de microfoon en vertel over je dag" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "2" }), _jsx("p", { children: "Ik maak automatisch taken aan van wat je zegt" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "3" }), _jsx("p", { children: "Je ziet je prioriteiten en planning voor vandaag" })] })] })] })] })),
    },
    {
        title: "📅 Rooster Tab - Je Planning Overzicht",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-green-50 rounded-lg", children: [_jsx(Calendar, { className: "w-8 h-8 text-green-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-green-800", children: "Wekelijks Overzicht" }), _jsx("p", { className: "text-sm text-green-600", children: "Alle taken, toetsen en deadlines in \u00E9\u00E9n overzicht" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Handige functies:" }), _jsxs("ul", { className: "space-y-2 text-sm", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Taken afvinken als je ze af hebt"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Prioriteit aanpassen (hoog, normaal, laag)"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Deadline bijhouden voor belangrijke dingen"] })] })] })] })),
    },
    {
        title: "➕ Toevoegen Tab - Handmatig Invoeren",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-orange-50 rounded-lg", children: [_jsx(Plus, { className: "w-8 h-8 text-orange-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-orange-800", children: "Rooster & Taken" }), _jsx("p", { className: "text-sm text-orange-600", children: "Voeg lessen, toetsen en huiswerk handmatig toe" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Wat kun je toevoegen?" }), _jsxs("div", { className: "grid grid-cols-2 gap-3 text-sm", children: [_jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDCDA Lessen" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Wiskunde, Nederlands, etc." })] }), _jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDCDD Toetsen" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Met datum en tijd" })] }), _jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDCCB Huiswerk" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Taken en opdrachten" })] }), _jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\u26BD Activiteiten" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Sport, hobby's, etc." })] })] })] })] })),
    },
    {
        title: "❓ Uitleg Tab - Je Huiswerkassistent",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-purple-50 rounded-lg", children: [_jsx(HelpCircle, { className: "w-8 h-8 text-purple-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-purple-800", children: "OCR + AI Hulp" }), _jsx("p", { className: "text-sm text-purple-600", children: "Maak een foto van je huiswerk en krijg uitleg" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Hoe gebruik je dit?" }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "1" }), _jsx("p", { children: "Maak een foto van je huiswerk of upload een PDF" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "2" }), _jsx("p", { children: "Ik lees de tekst en begrijp de vraag" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "3" }), _jsx("p", { children: "Je krijgt stap-voor-stap uitleg en voorbeelden" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "4" }), _jsx("p", { children: "Test jezelf met een kleine quiz" })] })] })] })] })),
    },
    {
        title: "⚙️ Instellingen Tab - Maak Het Jouw App",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-gray-50 rounded-lg", children: [_jsx(Settings, { className: "w-8 h-8 text-gray-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-gray-800", children: "Personalisatie" }), _jsx("p", { className: "text-sm text-gray-600", children: "Stel de app in zoals jij het fijn vindt" })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-3 text-sm", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("h5", { className: "font-medium", children: "\uD83C\uDFA8 App Kleuren" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Paars, blauw, groen of roze" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDCDA Jaargang" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "VMBO, HAVO, VWO, MBO" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDD14 Meldingen" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Dagelijkse herinneringen" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDCC5 Import" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "iCal rooster import" })] })] })] })),
    },
    {
        title: "💡 Tips voor Optimaal Gebruik",
        content: (_jsx("div", { className: "space-y-4", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "p-3 bg-yellow-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-yellow-800 mb-2", children: "\uD83C\uDF05 Begin je dag goed" }), _jsx("p", { className: "text-sm text-yellow-700", children: "Doe elke ochtend een voice check-in. Vertel wat je gisteren hebt gedaan en wat je vandaag wilt bereiken." })] }), _jsxs("div", { className: "p-3 bg-blue-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-blue-800 mb-2", children: "\uD83D\uDCF1 Gebruik foto's" }), _jsx("p", { className: "text-sm text-blue-700", children: "Als je ergens niet uitkomt, maak een foto van de opdracht. Ik geef je dan stap-voor-stap uitleg." })] }), _jsxs("div", { className: "p-3 bg-indigo-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-indigo-800 mb-2", children: "\uD83D\uDCC5 SomToday rooster" }), _jsx("p", { className: "text-sm text-indigo-700", children: "Gebruik je SomToday? Exporteer je rooster als iCal URL en importeer het in \u00E9\u00E9n keer via het Rooster tabblad!" })] }), _jsxs("div", { className: "p-3 bg-green-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-green-800 mb-2", children: "\uD83D\uDC68 \uD83D\uDC69 \uD83D\uDC67 \uD83D\uDC66 Betrek je ouders" }), _jsx("p", { className: "text-sm text-green-700", children: "Je ouders kunnen een eigen account maken om je voortgang te volgen. Vraag het ze!" })] }), _jsxs("div", { className: "p-3 bg-purple-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-purple-800 mb-2", children: "\uD83D\uDD04 Wees consistent" }), _jsx("p", { className: "text-sm text-purple-700", children: "Hoe meer je de app gebruikt, hoe beter ik je kan helpen. Probeer het elke dag even te checken." })] })] }) })),
    },
];
export default function AppIntroModal({ open, onOpenChange }) {
    const [currentStep, setCurrentStep] = useState(0);
    const nextStep = () => { if (currentStep < introSteps.length - 1)
        setCurrentStep(currentStep + 1); };
    const prevStep = () => { if (currentStep > 0)
        setCurrentStep(currentStep - 1); };
    const handleClose = () => { setCurrentStep(0); onOpenChange(false); };
    return (_jsx(Dialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(DialogContent, { className: "sm:max-w-md w-[min(680px,calc(100vw-2rem))] max-h-[85vh] overflow-y-auto rounded-2xl", "data-testid": "app-intro-modal", children: [_jsxs(DialogHeader, { children: [_jsx(DialogTitle, { className: "text-center", children: introSteps[currentStep].title }), _jsxs(DialogDescription, { className: "text-center", children: ["Stap ", currentStep + 1, " van ", introSteps.length] })] }), _jsx("div", { className: "py-4", children: introSteps[currentStep].content }), _jsx(Separator, {}), _jsxs("div", { className: "flex items-center justify-between pt-4", children: [_jsxs(Button, { variant: "outline", onClick: prevStep, disabled: currentStep === 0, className: "flex items-center gap-2", "data-testid": "button-prev-step", children: [_jsx(ChevronLeft, { className: "w-4 h-4" }), "Vorige"] }), _jsx("div", { className: "flex gap-2", children: introSteps.map((_, index) => (_jsx("div", { className: `w-2 h-2 rounded-full transition-colors ${index === currentStep ? "bg-primary" : "bg-muted"}` }, index))) }), currentStep < introSteps.length - 1 ? (_jsxs(Button, { onClick: nextStep, className: "flex items-center gap-2", "data-testid": "button-next-step", children: ["Volgende", _jsx(ChevronRight, { className: "w-4 h-4" })] })) : (_jsxs(Button, { onClick: handleClose, className: "flex items-center gap-2", "data-testid": "button-close-intro", children: ["Start!", _jsx(CheckCircle, { className: "w-4 h-4" })] }))] })] }) }));
}
