import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { TrendingUp, Bell, Heart, CheckCircle, ChevronLeft, ChevronRight, UserPlus, } from "lucide-react";
const parentIntroSteps = [
    {
        title: "Welkom Ouder! 👨 👩 👧 👦",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-muted-foreground", children: "Fijn dat je meedoet! Als ouder kun je je kind ondersteunen door hun voortgang te volgen en inzicht te krijgen in hun huiswerkgewoonten." }), _jsxs("div", { className: "bg-blue-50 p-4 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-blue-800 mb-2", children: "Wat kun je als ouder doen?" }), _jsxs("ul", { className: "space-y-2 text-sm text-blue-700", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Je kind koppelen aan jouw account"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Huiswerk voortgang bekijken"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Komende toetsen en deadlines zien"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), "Inzicht in dagelijkse check-ins"] })] })] })] })),
    },
    {
        title: "👥 Je Kind Koppelen",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-green-50 rounded-lg", children: [_jsx(UserPlus, { className: "w-8 h-8 text-green-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-green-800", children: "Account Koppeling" }), _jsx("p", { className: "text-sm text-green-600", children: "Verbind met het account van je kind" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Hoe werkt het koppelen?" }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "1" }), _jsx("p", { children: "Vul de email van je kind in bij \"Kind Toevoegen\"" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "2" }), _jsx("p", { children: "Je kind krijgt een notificatie om jou te bevestigen" })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(Badge, { variant: "outline", className: "mt-1", children: "3" }), _jsx("p", { children: "Na bevestiging zie je hun voortgang hier" })] })] })] }), _jsx("div", { className: "bg-orange-50 p-3 rounded-lg", children: _jsxs("p", { className: "text-sm text-orange-800", children: ["\uD83D\uDCA1 ", _jsx("strong", { children: "Tip:" }), " Je kind heeft controle en moet jou eerst bevestigen voor privacy."] }) })] })),
    },
    {
        title: "📊 Voortgang Bekijken",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-purple-50 rounded-lg", children: [_jsx(TrendingUp, { className: "w-8 h-8 text-purple-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-purple-800", children: "Inzicht & Overzicht" }), _jsx("p", { className: "text-sm text-purple-600", children: "Volg hoe je kind het doet met huiswerk" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Wat zie je allemaal?" }), _jsxs("div", { className: "grid grid-cols-2 gap-3 text-sm", children: [_jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\u2705 Voltooide Taken" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Afgevinkte huiswerk" })] }), _jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\u23F0 Komende Toetsen" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Belangrijke deadlines" })] }), _jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\uD83C\uDF99\uFE0F Voice Check-ins" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Dagelijkse reflecties" })] }), _jsxs("div", { className: "p-2 bg-gray-50 rounded", children: [_jsx("h5", { className: "font-medium", children: "\uD83D\uDCC8 Trends" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Voortgang over tijd" })] })] })] })] })),
    },
    {
        title: "🔔 Meldingen & Updates",
        content: (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-3 bg-yellow-50 rounded-lg", children: [_jsx(Bell, { className: "w-8 h-8 text-yellow-600" }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-yellow-800", children: "Automatische Updates" }), _jsx("p", { className: "text-sm text-yellow-600", children: "Blijf op de hoogte zonder te bemoeien" })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h4", { className: "font-semibold", children: "Wanneer krijg je meldingen?" }), _jsxs("ul", { className: "space-y-2 text-sm", children: [_jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Wanneer je kind een toets heeft voltooid"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Bij belangrijke deadlines die dichtbij komen"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Als je kind een paar dagen geen check-in heeft gedaan"] }), _jsxs("li", { className: "flex items-center gap-2", children: [_jsx(CheckCircle, { className: "w-4 h-4 text-green-600" }), "Weekly summary van de voortgang"] })] })] }), _jsx("div", { className: "bg-blue-50 p-3 rounded-lg", children: _jsxs("p", { className: "text-sm text-blue-800", children: ["\uD83D\uDCF1 ", _jsx("strong", { children: "Privacy eerst:" }), " Je ziet voortgang, niet de inhoud van gesprekken."] }) })] })),
    },
    {
        title: "💡 Tips voor Ouders",
        content: (_jsx("div", { className: "space-y-4", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "p-3 bg-green-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-green-800 mb-2", children: "\uD83C\uDFAF Stimuleer zelfstandigheid" }), _jsx("p", { className: "text-sm text-green-700", children: "Laat je kind zelf de app gebruiken. Jij kijkt mee, zij doen het werk. Dit helpt hen zelfstandiger te worden." })] }), _jsxs("div", { className: "p-3 bg-blue-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-blue-800 mb-2", children: "\uD83D\uDCAC Bespreek de voortgang" }), _jsx("p", { className: "text-sm text-blue-700", children: "Gebruik wat je hier ziet als gespreksstarter. \"Ik zag dat je veel wiskunde hebt gedaan deze week!\"" })] }), _jsxs("div", { className: "p-3 bg-purple-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-purple-800 mb-2", children: "\uD83C\uDFC6 Vier successen" }), _jsx("p", { className: "text-sm text-purple-700", children: "Complimenteer je kind wanneer je ziet dat ze consistent bezig zijn, ook met kleine stapjes." })] }), _jsxs("div", { className: "p-3 bg-orange-50 rounded-lg", children: [_jsx("h4", { className: "font-semibold text-orange-800 mb-2", children: "\uD83E\uDD1D Ondersteun bij problemen" }), _jsx("p", { className: "text-sm text-orange-700", children: "Als je ziet dat er weinig activiteit is, vraag hoe je kunt helpen in plaats van direct in te grijpen." })] })] }) })),
    },
];
export default function ParentIntroModal({ open, onOpenChange }) {
    const [currentStep, setCurrentStep] = useState(0);
    const nextStep = () => {
        if (currentStep < parentIntroSteps.length - 1) {
            setCurrentStep(currentStep + 1);
        }
    };
    const prevStep = () => {
        if (currentStep > 0) {
            setCurrentStep(currentStep - 1);
        }
    };
    const handleClose = () => {
        setCurrentStep(0);
        onOpenChange(false);
    };
    return (_jsx(Dialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(DialogContent, { className: "max-w-md max-h-[80vh] overflow-y-auto", "data-testid": "parent-intro-modal", children: [_jsxs(DialogHeader, { children: [_jsx(DialogTitle, { className: "text-center", children: parentIntroSteps[currentStep].title }), _jsxs(DialogDescription, { className: "text-center", children: ["Stap ", currentStep + 1, " van ", parentIntroSteps.length] })] }), _jsx("div", { className: "py-4", children: parentIntroSteps[currentStep].content }), _jsx(Separator, {}), _jsxs("div", { className: "flex items-center justify-between pt-4", children: [_jsxs(Button, { variant: "outline", onClick: prevStep, disabled: currentStep === 0, className: "flex items-center gap-2", "data-testid": "button-prev-step", children: [_jsx(ChevronLeft, { className: "w-4 h-4" }), "Vorige"] }), _jsx("div", { className: "flex gap-2", children: parentIntroSteps.map((_, index) => (_jsx("div", { className: `w-2 h-2 rounded-full transition-colors ${index === currentStep ? 'bg-primary' : 'bg-muted'}` }, index))) }), currentStep < parentIntroSteps.length - 1 ? (_jsxs(Button, { onClick: nextStep, className: "flex items-center gap-2", "data-testid": "button-next-step", children: ["Volgende", _jsx(ChevronRight, { className: "w-4 h-4" })] })) : (_jsxs(Button, { onClick: handleClose, className: "flex items-center gap-2", "data-testid": "button-close-intro", children: ["Begin!", _jsx(Heart, { className: "w-4 h-4" })] }))] })] }) }));
}
